.\"
.\" Copyright (c) 2018 Martin Pieuchot <mpi@grenadille.net>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: February 1 2018 $
.Dt GLA11Y 1
.Os
.Sh NAME
.Nm gla11y
.Nd check accessibility of glade widgets
.Sh SYNOPSIS
.Nm
.Op Fl hp
.Op Fl i Ar widgets
.Op Fl l Ar log
.Ar file
.Op file ...
.Sh DESCRIPTION
The
.Nm
utility check if
.Ar file
respect glade accessibility rules.
It prints messages for every error it encounters.
.Pp
The options are as follows:
.Bl -tag -width -i_widgets
.It Fl h
Show help message and exit.
.It Fl i Ar widgets
Do not check elements whose class is listed in
.Ar widgets .
By default the following widgets are ignored: GtkBox, GtkVBox
.It Fl I
Do not ignore any widget.
.It Fl l Ar log
Append error messages to
.Ar log
file instead of printing them to stdout.
.It Fl p
Print class paths instead of line numbers in messages.
.It Fl W
Make all warnings into errors.
.El
.Sh EXIT STATUS
.Ex -std gla11y
.Sh EXAMPLES
To check all the widgets but GtkLabel and AtkObject in file the sortdialog.ui:
.Bd -literal -offset indent
gla11y -i GtkLabel,AtkObject sortdialog.ui
.Ed
.Sh AUTHORS
.An Martin Pieuchot Aq Mt mpi@grenadille.net
